### PR TITLE
Add scan2html

### PR DESCRIPTION
**Pull request by fatihtokus**

### CODE REVIEW

**Comment by knqyf263** [comment]
Thanks for your contribution. Could you fix your manifest according to https://github.com/aquasecurity/trivy-plugin-index/pull/10? Sorry for the confusion, the index is still in the early stages and not mature yet.

**Comment by fatihtokus** [comment]
No problem, It is done

**Comment by knqyf263** [comment]
Thanks. Could you rebase the main branch so we can ensure the test passes with the latest commit?

**Comment by fatihtokus** [comment]
I have updated my branch with the latest

**Comment by knqyf263** [comment]
Thanks!

**Pull request merged**
